/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VpRouteImport } from './routes/$vp'
import { Route as BangGiaRouteImport } from './routes/bang-gia'
import { Route as BaoCaoDoanhThuRouteImport } from './routes/bao-cao-doanh-thu'
import { Route as BaoCaoGioRouteImport } from './routes/bao-cao-gio'
import { Route as BaoCaoThuRouteImport } from './routes/bao-cao-thu'
import { Route as BaoGioXeRouteImport } from './routes/bao-gio-xe'
import { Route as BaoTriRouteImport } from './routes/bao-tri'
import { Route as ChamCongRouteImport } from './routes/cham-cong'
import { Route as ChoBanGiaoRouteImport } from './routes/cho-ban-giao'
import { Route as CrmSdtRouteImport } from './routes/crm-sdt'
import { Route as ChuyenRouteImport } from './routes/chuyen'
import { Route as DanhSachPhieuThuRouteImport } from './routes/danh-sach-phieu-thu'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DayShipRouteImport } from './routes/day-ship'
import { Route as DieuChinhRouteImport } from './routes/dieu-chinh'
import { Route as DoiSoatRouteImport } from './routes/doi-soat'
import { Route as DonHoanRouteImport } from './routes/don-hoan'
import { Route as DonHuyRouteImport } from './routes/don-huy'
import { Route as DuyetHuyRouteImport } from './routes/duyet-huy'
import { Route as GiaoTanNhaRouteImport } from './routes/giao-tan-nha'
import { Route as GiaoThanhCongRouteImport } from './routes/giao-thanh-cong'
import { Route as HangChoLenXeRouteImport } from './routes/hang-cho-len-xe'
import { Route as HangSapVeRouteImport } from './routes/hang-sap-ve'
import { Route as HoanHangRouteImport } from './routes/hoan-hang'
import { Route as KiemKeRouteImport } from './routes/kiem-ke'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterRouteImport } from './routes/master'
import { Route as NgoaiLeRouteImport } from './routes/ngoai-le'
import { Route as NhapKhoLuanChuyenRouteImport } from './routes/nhap-kho-luan-chuyen'
import { Route as NhomQuyenRouteImport } from './routes/nhom-quyen'
import { Route as PhienDangNhapRouteImport } from './routes/phien-dang-nhap'
import { Route as PhieuThuRouteImport } from './routes/phieu-thu'
import { Route as PhuPhiRouteImport } from './routes/phu-phi'
import { Route as PodQuayRouteImport } from './routes/pod-quay'
import { Route as QuanLyDonCodRouteImport } from './routes/quan-ly-don-cod'
import { Route as QuanLyHoaDonRouteImport } from './routes/quan-ly-hoa-don'
import { Route as QuetNhapRouteImport } from './routes/quet-nhap'
import { Route as QuetXuatRouteImport } from './routes/quet-xuat'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TacVuRouteImport } from './routes/tac-vu'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as TaoDonRouteImport } from './routes/tao-don'
import { Route as TichHopRouteImport } from './routes/tich-hop'
import { Route as TonKhoRouteImport } from './routes/ton-kho'
import { Route as TraCuuRouteImport } from './routes/tra-cuu'
import { Route as LayHangRouteImport } from './routes/lay-hang'
import { Route as ManHinhQrKeyRouteImport } from './routes/man-hinh-qr.$key'
import { Route as VanDonRouteImport } from './routes/van-don'
import { Route as TaoDonVpRouteImport } from './routes/tao-don_.$vp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VpRoute = VpRouteImport.update({
  id: '/$vp',
  path: '/$vp',
  getParentRoute: () => rootRouteImport,
} as any)
const BangGiaRoute = BangGiaRouteImport.update({
  id: '/bang-gia',
  path: '/bang-gia',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoCaoDoanhThuRoute = BaoCaoDoanhThuRouteImport.update({
  id: '/bao-cao-doanh-thu',
  path: '/bao-cao-doanh-thu',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoCaoGioRoute = BaoCaoGioRouteImport.update({
  id: '/bao-cao-gio',
  path: '/bao-cao-gio',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoCaoThuRoute = BaoCaoThuRouteImport.update({
  id: '/bao-cao-thu',
  path: '/bao-cao-thu',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoGioXeRoute = BaoGioXeRouteImport.update({
  id: '/bao-gio-xe',
  path: '/bao-gio-xe',
  getParentRoute: () => rootRouteImport,
} as any)
const BaoTriRoute = BaoTriRouteImport.update({
  id: '/bao-tri',
  path: '/bao-tri',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamCongRoute = ChamCongRouteImport.update({
  id: '/cham-cong',
  path: '/cham-cong',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSdtRoute = CrmSdtRouteImport.update({
  id: '/crm-sdt',
  path: '/crm-sdt',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoBanGiaoRoute = ChoBanGiaoRouteImport.update({
  id: '/cho-ban-giao',
  path: '/cho-ban-giao',
  getParentRoute: () => rootRouteImport,
} as any)
const ChuyenRoute = ChuyenRouteImport.update({
  id: '/chuyen',
  path: '/chuyen',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhSachPhieuThuRoute = DanhSachPhieuThuRouteImport.update({
  id: '/danh-sach-phieu-thu',
  path: '/danh-sach-phieu-thu',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DayShipRoute = DayShipRouteImport.update({
  id: '/day-ship',
  path: '/day-ship',
  getParentRoute: () => rootRouteImport,
} as any)
const DieuChinhRoute = DieuChinhRouteImport.update({
  id: '/dieu-chinh',
  path: '/dieu-chinh',
  getParentRoute: () => rootRouteImport,
} as any)
const DoiSoatRoute = DoiSoatRouteImport.update({
  id: '/doi-soat',
  path: '/doi-soat',
  getParentRoute: () => rootRouteImport,
} as any)
const DonHoanRoute = DonHoanRouteImport.update({
  id: '/don-hoan',
  path: '/don-hoan',
  getParentRoute: () => rootRouteImport,
} as any)
const DonHuyRoute = DonHuyRouteImport.update({
  id: '/don-huy',
  path: '/don-huy',
  getParentRoute: () => rootRouteImport,
} as any)
const DuyetHuyRoute = DuyetHuyRouteImport.update({
  id: '/duyet-huy',
  path: '/duyet-huy',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaoTanNhaRoute = GiaoTanNhaRouteImport.update({
  id: '/giao-tan-nha',
  path: '/giao-tan-nha',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaoThanhCongRoute = GiaoThanhCongRouteImport.update({
  id: '/giao-thanh-cong',
  path: '/giao-thanh-cong',
  getParentRoute: () => rootRouteImport,
} as any)
const HangChoLenXeRoute = HangChoLenXeRouteImport.update({
  id: '/hang-cho-len-xe',
  path: '/hang-cho-len-xe',
  getParentRoute: () => rootRouteImport,
} as any)
const HangSapVeRoute = HangSapVeRouteImport.update({
  id: '/hang-sap-ve',
  path: '/hang-sap-ve',
  getParentRoute: () => rootRouteImport,
} as any)
const HoanHangRoute = HoanHangRouteImport.update({
  id: '/hoan-hang',
  path: '/hoan-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const KiemKeRoute = KiemKeRouteImport.update({
  id: '/kiem-ke',
  path: '/kiem-ke',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoaiLeRoute = NgoaiLeRouteImport.update({
  id: '/ngoai-le',
  path: '/ngoai-le',
  getParentRoute: () => rootRouteImport,
} as any)
const NhapKhoLuanChuyenRoute = NhapKhoLuanChuyenRouteImport.update({
  id: '/nhap-kho-luan-chuyen',
  path: '/nhap-kho-luan-chuyen',
  getParentRoute: () => rootRouteImport,
} as any)
const NhomQuyenRoute = NhomQuyenRouteImport.update({
  id: '/nhom-quyen',
  path: '/nhom-quyen',
  getParentRoute: () => rootRouteImport,
} as any)
const PhienDangNhapRoute = PhienDangNhapRouteImport.update({
  id: '/phien-dang-nhap',
  path: '/phien-dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const PhieuThuRoute = PhieuThuRouteImport.update({
  id: '/phieu-thu',
  path: '/phieu-thu',
  getParentRoute: () => rootRouteImport,
} as any)
const PhuPhiRoute = PhuPhiRouteImport.update({
  id: '/phu-phi',
  path: '/phu-phi',
  getParentRoute: () => rootRouteImport,
} as any)
const PodQuayRoute = PodQuayRouteImport.update({
  id: '/pod-quay',
  path: '/pod-quay',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyDonCodRoute = QuanLyDonCodRouteImport.update({
  id: '/quan-ly-don-cod',
  path: '/quan-ly-don-cod',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyHoaDonRoute = QuanLyHoaDonRouteImport.update({
  id: '/quan-ly-hoa-don',
  path: '/quan-ly-hoa-don',
  getParentRoute: () => rootRouteImport,
} as any)
const QuetNhapRoute = QuetNhapRouteImport.update({
  id: '/quet-nhap',
  path: '/quet-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const QuetXuatRoute = QuetXuatRouteImport.update({
  id: '/quet-xuat',
  path: '/quet-xuat',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TacVuRoute = TacVuRouteImport.update({
  id: '/tac-vu',
  path: '/tac-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const TaoDonRoute = TaoDonRouteImport.update({
  id: '/tao-don',
  path: '/tao-don',
  getParentRoute: () => rootRouteImport,
} as any)
const TichHopRoute = TichHopRouteImport.update({
  id: '/tich-hop',
  path: '/tich-hop',
  getParentRoute: () => rootRouteImport,
} as any)
const TonKhoRoute = TonKhoRouteImport.update({
  id: '/ton-kho',
  path: '/ton-kho',
  getParentRoute: () => rootRouteImport,
} as any)
const TraCuuRoute = TraCuuRouteImport.update({
  id: '/tra-cuu',
  path: '/tra-cuu',
  getParentRoute: () => rootRouteImport,
} as any)
const LayHangRoute = LayHangRouteImport.update({
  id: '/lay-hang',
  path: '/lay-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const ManHinhQrKeyRoute = ManHinhQrKeyRouteImport.update({
  id: '/man-hinh-qr/$key',
  path: '/man-hinh-qr/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const VanDonRoute = VanDonRouteImport.update({
  id: '/van-don',
  path: '/van-don',
  getParentRoute: () => rootRouteImport,
} as any)
const TaoDonVpRoute = TaoDonVpRouteImport.update({
  id: '/tao-don_/$vp',
  path: '/tao-don/$vp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$vp': typeof VpRoute
  '/bang-gia': typeof BangGiaRoute
  '/bao-cao-doanh-thu': typeof BaoCaoDoanhThuRoute
  '/bao-cao-gio': typeof BaoCaoGioRoute
  '/bao-cao-thu': typeof BaoCaoThuRoute
  '/bao-gio-xe': typeof BaoGioXeRoute
  '/bao-tri': typeof BaoTriRoute
  '/cham-cong': typeof ChamCongRoute
  '/crm-sdt': typeof CrmSdtRoute
  '/cho-ban-giao': typeof ChoBanGiaoRoute
  '/chuyen': typeof ChuyenRoute
  '/danh-sach-phieu-thu': typeof DanhSachPhieuThuRoute
  '/dashboard': typeof DashboardRoute
  '/day-ship': typeof DayShipRoute
  '/dieu-chinh': typeof DieuChinhRoute
  '/doi-soat': typeof DoiSoatRoute
  '/don-hoan': typeof DonHoanRoute
  '/don-huy': typeof DonHuyRoute
  '/duyet-huy': typeof DuyetHuyRoute
  '/giao-tan-nha': typeof GiaoTanNhaRoute
  '/giao-thanh-cong': typeof GiaoThanhCongRoute
  '/hang-cho-len-xe': typeof HangChoLenXeRoute
  '/hang-sap-ve': typeof HangSapVeRoute
  '/hoan-hang': typeof HoanHangRoute
  '/kiem-ke': typeof KiemKeRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/ngoai-le': typeof NgoaiLeRoute
  '/nhap-kho-luan-chuyen': typeof NhapKhoLuanChuyenRoute
  '/nhom-quyen': typeof NhomQuyenRoute
  '/phien-dang-nhap': typeof PhienDangNhapRoute
  '/phieu-thu': typeof PhieuThuRoute
  '/phu-phi': typeof PhuPhiRoute
  '/pod-quay': typeof PodQuayRoute
  '/quan-ly-don-cod': typeof QuanLyDonCodRoute
  '/quan-ly-hoa-don': typeof QuanLyHoaDonRoute
  '/quet-nhap': typeof QuetNhapRoute
  '/quet-xuat': typeof QuetXuatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tac-vu': typeof TacVuRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tao-don': typeof TaoDonRoute
  '/tich-hop': typeof TichHopRoute
  '/ton-kho': typeof TonKhoRoute
  '/tra-cuu': typeof TraCuuRoute
  '/lay-hang': typeof LayHangRoute
  '/man-hinh-qr/$key': typeof ManHinhQrKeyRoute
  '/van-don': typeof VanDonRoute
  '/tao-don/$vp': typeof TaoDonVpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$vp': typeof VpRoute
  '/bang-gia': typeof BangGiaRoute
  '/bao-cao-doanh-thu': typeof BaoCaoDoanhThuRoute
  '/bao-cao-gio': typeof BaoCaoGioRoute
  '/bao-cao-thu': typeof BaoCaoThuRoute
  '/bao-gio-xe': typeof BaoGioXeRoute
  '/bao-tri': typeof BaoTriRoute
  '/cham-cong': typeof ChamCongRoute
  '/crm-sdt': typeof CrmSdtRoute
  '/cho-ban-giao': typeof ChoBanGiaoRoute
  '/chuyen': typeof ChuyenRoute
  '/danh-sach-phieu-thu': typeof DanhSachPhieuThuRoute
  '/dashboard': typeof DashboardRoute
  '/day-ship': typeof DayShipRoute
  '/dieu-chinh': typeof DieuChinhRoute
  '/doi-soat': typeof DoiSoatRoute
  '/don-hoan': typeof DonHoanRoute
  '/don-huy': typeof DonHuyRoute
  '/duyet-huy': typeof DuyetHuyRoute
  '/giao-tan-nha': typeof GiaoTanNhaRoute
  '/giao-thanh-cong': typeof GiaoThanhCongRoute
  '/hang-cho-len-xe': typeof HangChoLenXeRoute
  '/hang-sap-ve': typeof HangSapVeRoute
  '/hoan-hang': typeof HoanHangRoute
  '/kiem-ke': typeof KiemKeRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/ngoai-le': typeof NgoaiLeRoute
  '/nhap-kho-luan-chuyen': typeof NhapKhoLuanChuyenRoute
  '/nhom-quyen': typeof NhomQuyenRoute
  '/phien-dang-nhap': typeof PhienDangNhapRoute
  '/phieu-thu': typeof PhieuThuRoute
  '/phu-phi': typeof PhuPhiRoute
  '/pod-quay': typeof PodQuayRoute
  '/quan-ly-don-cod': typeof QuanLyDonCodRoute
  '/quan-ly-hoa-don': typeof QuanLyHoaDonRoute
  '/quet-nhap': typeof QuetNhapRoute
  '/quet-xuat': typeof QuetXuatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tac-vu': typeof TacVuRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tao-don': typeof TaoDonRoute
  '/tich-hop': typeof TichHopRoute
  '/ton-kho': typeof TonKhoRoute
  '/tra-cuu': typeof TraCuuRoute
  '/lay-hang': typeof LayHangRoute
  '/man-hinh-qr/$key': typeof ManHinhQrKeyRoute
  '/van-don': typeof VanDonRoute
  '/tao-don/$vp': typeof TaoDonVpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$vp': typeof VpRoute
  '/bang-gia': typeof BangGiaRoute
  '/bao-cao-doanh-thu': typeof BaoCaoDoanhThuRoute
  '/bao-cao-gio': typeof BaoCaoGioRoute
  '/bao-cao-thu': typeof BaoCaoThuRoute
  '/bao-gio-xe': typeof BaoGioXeRoute
  '/bao-tri': typeof BaoTriRoute
  '/cham-cong': typeof ChamCongRoute
  '/crm-sdt': typeof CrmSdtRoute
  '/cho-ban-giao': typeof ChoBanGiaoRoute
  '/chuyen': typeof ChuyenRoute
  '/danh-sach-phieu-thu': typeof DanhSachPhieuThuRoute
  '/dashboard': typeof DashboardRoute
  '/day-ship': typeof DayShipRoute
  '/dieu-chinh': typeof DieuChinhRoute
  '/doi-soat': typeof DoiSoatRoute
  '/don-hoan': typeof DonHoanRoute
  '/don-huy': typeof DonHuyRoute
  '/duyet-huy': typeof DuyetHuyRoute
  '/giao-tan-nha': typeof GiaoTanNhaRoute
  '/giao-thanh-cong': typeof GiaoThanhCongRoute
  '/hang-cho-len-xe': typeof HangChoLenXeRoute
  '/hang-sap-ve': typeof HangSapVeRoute
  '/hoan-hang': typeof HoanHangRoute
  '/kiem-ke': typeof KiemKeRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/ngoai-le': typeof NgoaiLeRoute
  '/nhap-kho-luan-chuyen': typeof NhapKhoLuanChuyenRoute
  '/nhom-quyen': typeof NhomQuyenRoute
  '/phien-dang-nhap': typeof PhienDangNhapRoute
  '/phieu-thu': typeof PhieuThuRoute
  '/phu-phi': typeof PhuPhiRoute
  '/pod-quay': typeof PodQuayRoute
  '/quan-ly-don-cod': typeof QuanLyDonCodRoute
  '/quan-ly-hoa-don': typeof QuanLyHoaDonRoute
  '/quet-nhap': typeof QuetNhapRoute
  '/quet-xuat': typeof QuetXuatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tac-vu': typeof TacVuRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tao-don': typeof TaoDonRoute
  '/tich-hop': typeof TichHopRoute
  '/ton-kho': typeof TonKhoRoute
  '/tra-cuu': typeof TraCuuRoute
  '/lay-hang': typeof LayHangRoute
  '/man-hinh-qr/$key': typeof ManHinhQrKeyRoute
  '/van-don': typeof VanDonRoute
  '/tao-don_/$vp': typeof TaoDonVpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$vp'
    | '/bang-gia'
    | '/bao-cao-doanh-thu'
    | '/bao-cao-gio'
    | '/bao-cao-thu'
    | '/bao-gio-xe'
    | '/bao-tri'
    | '/cham-cong'
    | '/crm-sdt'
    | '/cho-ban-giao'
    | '/chuyen'
    | '/danh-sach-phieu-thu'
    | '/dashboard'
    | '/day-ship'
    | '/dieu-chinh'
    | '/doi-soat'
    | '/don-hoan'
    | '/don-huy'
    | '/duyet-huy'
    | '/giao-tan-nha'
    | '/giao-thanh-cong'
    | '/hang-cho-len-xe'
    | '/hang-sap-ve'
    | '/hoan-hang'
    | '/kiem-ke'
    | '/login'
    | '/master'
    | '/ngoai-le'
    | '/nhap-kho-luan-chuyen'
    | '/nhom-quyen'
    | '/phien-dang-nhap'
    | '/phieu-thu'
    | '/phu-phi'
    | '/pod-quay'
    | '/quan-ly-don-cod'
    | '/quan-ly-hoa-don'
    | '/quet-nhap'
    | '/quet-xuat'
    | '/sitemap.xml'
    | '/tac-vu'
    | '/tai-khoan'
    | '/tao-don'
    | '/tich-hop'
    | '/ton-kho'
    | '/tra-cuu'
    | '/lay-hang'
    | '/man-hinh-qr/$key'
    | '/van-don'
    | '/tao-don/$vp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$vp'
    | '/bang-gia'
    | '/bao-cao-doanh-thu'
    | '/bao-cao-gio'
    | '/bao-cao-thu'
    | '/bao-gio-xe'
    | '/bao-tri'
    | '/cham-cong'
    | '/crm-sdt'
    | '/cho-ban-giao'
    | '/chuyen'
    | '/danh-sach-phieu-thu'
    | '/dashboard'
    | '/day-ship'
    | '/dieu-chinh'
    | '/doi-soat'
    | '/don-hoan'
    | '/don-huy'
    | '/duyet-huy'
    | '/giao-tan-nha'
    | '/giao-thanh-cong'
    | '/hang-cho-len-xe'
    | '/hang-sap-ve'
    | '/hoan-hang'
    | '/kiem-ke'
    | '/login'
    | '/master'
    | '/ngoai-le'
    | '/nhap-kho-luan-chuyen'
    | '/nhom-quyen'
    | '/phien-dang-nhap'
    | '/phieu-thu'
    | '/phu-phi'
    | '/pod-quay'
    | '/quan-ly-don-cod'
    | '/quan-ly-hoa-don'
    | '/quet-nhap'
    | '/quet-xuat'
    | '/sitemap.xml'
    | '/tac-vu'
    | '/tai-khoan'
    | '/tao-don'
    | '/tich-hop'
    | '/ton-kho'
    | '/tra-cuu'
    | '/lay-hang'
    | '/man-hinh-qr/$key'
    | '/van-don'
    | '/tao-don/$vp'
  id:
    | '__root__'
    | '/'
    | '/$vp'
    | '/bang-gia'
    | '/bao-cao-doanh-thu'
    | '/bao-cao-gio'
    | '/bao-cao-thu'
    | '/bao-gio-xe'
    | '/bao-tri'
    | '/cham-cong'
    | '/crm-sdt'
    | '/cho-ban-giao'
    | '/chuyen'
    | '/danh-sach-phieu-thu'
    | '/dashboard'
    | '/day-ship'
    | '/dieu-chinh'
    | '/doi-soat'
    | '/don-hoan'
    | '/don-huy'
    | '/duyet-huy'
    | '/giao-tan-nha'
    | '/giao-thanh-cong'
    | '/hang-cho-len-xe'
    | '/hang-sap-ve'
    | '/hoan-hang'
    | '/kiem-ke'
    | '/login'
    | '/master'
    | '/ngoai-le'
    | '/nhap-kho-luan-chuyen'
    | '/nhom-quyen'
    | '/phien-dang-nhap'
    | '/phieu-thu'
    | '/phu-phi'
    | '/pod-quay'
    | '/quan-ly-don-cod'
    | '/quan-ly-hoa-don'
    | '/quet-nhap'
    | '/quet-xuat'
    | '/sitemap.xml'
    | '/tac-vu'
    | '/tai-khoan'
    | '/tao-don'
    | '/tich-hop'
    | '/ton-kho'
    | '/tra-cuu'
    | '/lay-hang'
    | '/man-hinh-qr/$key'
    | '/van-don'
    | '/tao-don_/$vp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VpRoute: typeof VpRoute
  BangGiaRoute: typeof BangGiaRoute
  BaoCaoDoanhThuRoute: typeof BaoCaoDoanhThuRoute
  BaoCaoGioRoute: typeof BaoCaoGioRoute
  BaoCaoThuRoute: typeof BaoCaoThuRoute
  BaoGioXeRoute: typeof BaoGioXeRoute
  BaoTriRoute: typeof BaoTriRoute
  ChamCongRoute: typeof ChamCongRoute
  CrmSdtRoute: typeof CrmSdtRoute
  ChoBanGiaoRoute: typeof ChoBanGiaoRoute
  ChuyenRoute: typeof ChuyenRoute
  DanhSachPhieuThuRoute: typeof DanhSachPhieuThuRoute
  DashboardRoute: typeof DashboardRoute
  DayShipRoute: typeof DayShipRoute
  DieuChinhRoute: typeof DieuChinhRoute
  DoiSoatRoute: typeof DoiSoatRoute
  DonHoanRoute: typeof DonHoanRoute
  DonHuyRoute: typeof DonHuyRoute
  DuyetHuyRoute: typeof DuyetHuyRoute
  GiaoTanNhaRoute: typeof GiaoTanNhaRoute
  GiaoThanhCongRoute: typeof GiaoThanhCongRoute
  HangChoLenXeRoute: typeof HangChoLenXeRoute
  HangSapVeRoute: typeof HangSapVeRoute
  HoanHangRoute: typeof HoanHangRoute
  KiemKeRoute: typeof KiemKeRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRoute
  NgoaiLeRoute: typeof NgoaiLeRoute
  NhapKhoLuanChuyenRoute: typeof NhapKhoLuanChuyenRoute
  NhomQuyenRoute: typeof NhomQuyenRoute
  PhienDangNhapRoute: typeof PhienDangNhapRoute
  PhieuThuRoute: typeof PhieuThuRoute
  PhuPhiRoute: typeof PhuPhiRoute
  PodQuayRoute: typeof PodQuayRoute
  QuanLyDonCodRoute: typeof QuanLyDonCodRoute
  QuanLyHoaDonRoute: typeof QuanLyHoaDonRoute
  QuetNhapRoute: typeof QuetNhapRoute
  QuetXuatRoute: typeof QuetXuatRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TacVuRoute: typeof TacVuRoute
  TaiKhoanRoute: typeof TaiKhoanRoute
  TaoDonRoute: typeof TaoDonRoute
  TichHopRoute: typeof TichHopRoute
  TonKhoRoute: typeof TonKhoRoute
  TraCuuRoute: typeof TraCuuRoute
  LayHangRoute: typeof LayHangRoute
  ManHinhQrKeyRoute: typeof ManHinhQrKeyRoute
  VanDonRoute: typeof VanDonRoute
  TaoDonVpRoute: typeof TaoDonVpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$vp': {
      id: '/$vp'
      path: '/$vp'
      fullPath: '/$vp'
      preLoaderRoute: typeof VpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang-gia': {
      id: '/bang-gia'
      path: '/bang-gia'
      fullPath: '/bang-gia'
      preLoaderRoute: typeof BangGiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-cao-doanh-thu': {
      id: '/bao-cao-doanh-thu'
      path: '/bao-cao-doanh-thu'
      fullPath: '/bao-cao-doanh-thu'
      preLoaderRoute: typeof BaoCaoDoanhThuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-cao-gio': {
      id: '/bao-cao-gio'
      path: '/bao-cao-gio'
      fullPath: '/bao-cao-gio'
      preLoaderRoute: typeof BaoCaoGioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-cao-thu': {
      id: '/bao-cao-thu'
      path: '/bao-cao-thu'
      fullPath: '/bao-cao-thu'
      preLoaderRoute: typeof BaoCaoThuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-gio-xe': {
      id: '/bao-gio-xe'
      path: '/bao-gio-xe'
      fullPath: '/bao-gio-xe'
      preLoaderRoute: typeof BaoGioXeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bao-tri': {
      id: '/bao-tri'
      path: '/bao-tri'
      fullPath: '/bao-tri'
      preLoaderRoute: typeof BaoTriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cham-cong': {
      id: '/cham-cong'
      path: '/cham-cong'
      fullPath: '/cham-cong'
      preLoaderRoute: typeof ChamCongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-sdt': {
      id: '/crm-sdt'
      path: '/crm-sdt'
      fullPath: '/crm-sdt'
      preLoaderRoute: typeof CrmSdtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cho-ban-giao': {
      id: '/cho-ban-giao'
      path: '/cho-ban-giao'
      fullPath: '/cho-ban-giao'
      preLoaderRoute: typeof ChoBanGiaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chuyen': {
      id: '/chuyen'
      path: '/chuyen'
      fullPath: '/chuyen'
      preLoaderRoute: typeof ChuyenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-sach-phieu-thu': {
      id: '/danh-sach-phieu-thu'
      path: '/danh-sach-phieu-thu'
      fullPath: '/danh-sach-phieu-thu'
      preLoaderRoute: typeof DanhSachPhieuThuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-ship': {
      id: '/day-ship'
      path: '/day-ship'
      fullPath: '/day-ship'
      preLoaderRoute: typeof DayShipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieu-chinh': {
      id: '/dieu-chinh'
      path: '/dieu-chinh'
      fullPath: '/dieu-chinh'
      preLoaderRoute: typeof DieuChinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doi-soat': {
      id: '/doi-soat'
      path: '/doi-soat'
      fullPath: '/doi-soat'
      preLoaderRoute: typeof DoiSoatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don-hoan': {
      id: '/don-hoan'
      path: '/don-hoan'
      fullPath: '/don-hoan'
      preLoaderRoute: typeof DonHoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don-huy': {
      id: '/don-huy'
      path: '/don-huy'
      fullPath: '/don-huy'
      preLoaderRoute: typeof DonHuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duyet-huy': {
      id: '/duyet-huy'
      path: '/duyet-huy'
      fullPath: '/duyet-huy'
      preLoaderRoute: typeof DuyetHuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giao-tan-nha': {
      id: '/giao-tan-nha'
      path: '/giao-tan-nha'
      fullPath: '/giao-tan-nha'
      preLoaderRoute: typeof GiaoTanNhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giao-thanh-cong': {
      id: '/giao-thanh-cong'
      path: '/giao-thanh-cong'
      fullPath: '/giao-thanh-cong'
      preLoaderRoute: typeof GiaoThanhCongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hang-cho-len-xe': {
      id: '/hang-cho-len-xe'
      path: '/hang-cho-len-xe'
      fullPath: '/hang-cho-len-xe'
      preLoaderRoute: typeof HangChoLenXeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hang-sap-ve': {
      id: '/hang-sap-ve'
      path: '/hang-sap-ve'
      fullPath: '/hang-sap-ve'
      preLoaderRoute: typeof HangSapVeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoan-hang': {
      id: '/hoan-hang'
      path: '/hoan-hang'
      fullPath: '/hoan-hang'
      preLoaderRoute: typeof HoanHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiem-ke': {
      id: '/kiem-ke'
      path: '/kiem-ke'
      fullPath: '/kiem-ke'
      preLoaderRoute: typeof KiemKeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngoai-le': {
      id: '/ngoai-le'
      path: '/ngoai-le'
      fullPath: '/ngoai-le'
      preLoaderRoute: typeof NgoaiLeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhap-kho-luan-chuyen': {
      id: '/nhap-kho-luan-chuyen'
      path: '/nhap-kho-luan-chuyen'
      fullPath: '/nhap-kho-luan-chuyen'
      preLoaderRoute: typeof NhapKhoLuanChuyenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhom-quyen': {
      id: '/nhom-quyen'
      path: '/nhom-quyen'
      fullPath: '/nhom-quyen'
      preLoaderRoute: typeof NhomQuyenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phien-dang-nhap': {
      id: '/phien-dang-nhap'
      path: '/phien-dang-nhap'
      fullPath: '/phien-dang-nhap'
      preLoaderRoute: typeof PhienDangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phieu-thu': {
      id: '/phieu-thu'
      path: '/phieu-thu'
      fullPath: '/phieu-thu'
      preLoaderRoute: typeof PhieuThuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phu-phi': {
      id: '/phu-phi'
      path: '/phu-phi'
      fullPath: '/phu-phi'
      preLoaderRoute: typeof PhuPhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pod-quay': {
      id: '/pod-quay'
      path: '/pod-quay'
      fullPath: '/pod-quay'
      preLoaderRoute: typeof PodQuayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly-don-cod': {
      id: '/quan-ly-don-cod'
      path: '/quan-ly-don-cod'
      fullPath: '/quan-ly-don-cod'
      preLoaderRoute: typeof QuanLyDonCodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly-hoa-don': {
      id: '/quan-ly-hoa-don'
      path: '/quan-ly-hoa-don'
      fullPath: '/quan-ly-hoa-don'
      preLoaderRoute: typeof QuanLyHoaDonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quet-nhap': {
      id: '/quet-nhap'
      path: '/quet-nhap'
      fullPath: '/quet-nhap'
      preLoaderRoute: typeof QuetNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quet-xuat': {
      id: '/quet-xuat'
      path: '/quet-xuat'
      fullPath: '/quet-xuat'
      preLoaderRoute: typeof QuetXuatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tac-vu': {
      id: '/tac-vu'
      path: '/tac-vu'
      fullPath: '/tac-vu'
      preLoaderRoute: typeof TacVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tao-don': {
      id: '/tao-don'
      path: '/tao-don'
      fullPath: '/tao-don'
      preLoaderRoute: typeof TaoDonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tich-hop': {
      id: '/tich-hop'
      path: '/tich-hop'
      fullPath: '/tich-hop'
      preLoaderRoute: typeof TichHopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ton-kho': {
      id: '/ton-kho'
      path: '/ton-kho'
      fullPath: '/ton-kho'
      preLoaderRoute: typeof TonKhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tra-cuu': {
      id: '/tra-cuu'
      path: '/tra-cuu'
      fullPath: '/tra-cuu'
      preLoaderRoute: typeof TraCuuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lay-hang': {
      id: '/lay-hang'
      path: '/lay-hang'
      fullPath: '/lay-hang'
      preLoaderRoute: typeof LayHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/man-hinh-qr/$key': {
      id: '/man-hinh-qr/$key'
      path: '/man-hinh-qr/$key'
      fullPath: '/man-hinh-qr/$key'
      preLoaderRoute: typeof ManHinhQrKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/van-don': {
      id: '/van-don'
      path: '/van-don'
      fullPath: '/van-don'
      preLoaderRoute: typeof VanDonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tao-don_/$vp': {
      id: '/tao-don_/$vp'
      path: '/tao-don/$vp'
      fullPath: '/tao-don/$vp'
      preLoaderRoute: typeof TaoDonVpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VpRoute: VpRoute,
  BangGiaRoute: BangGiaRoute,
  BaoCaoDoanhThuRoute: BaoCaoDoanhThuRoute,
  BaoCaoGioRoute: BaoCaoGioRoute,
  BaoCaoThuRoute: BaoCaoThuRoute,
  BaoGioXeRoute: BaoGioXeRoute,
  BaoTriRoute: BaoTriRoute,
  ChamCongRoute: ChamCongRoute,
  CrmSdtRoute: CrmSdtRoute,
  ChoBanGiaoRoute: ChoBanGiaoRoute,
  ChuyenRoute: ChuyenRoute,
  DanhSachPhieuThuRoute: DanhSachPhieuThuRoute,
  DashboardRoute: DashboardRoute,
  DayShipRoute: DayShipRoute,
  DieuChinhRoute: DieuChinhRoute,
  DoiSoatRoute: DoiSoatRoute,
  DonHoanRoute: DonHoanRoute,
  DonHuyRoute: DonHuyRoute,
  DuyetHuyRoute: DuyetHuyRoute,
  GiaoTanNhaRoute: GiaoTanNhaRoute,
  GiaoThanhCongRoute: GiaoThanhCongRoute,
  HangChoLenXeRoute: HangChoLenXeRoute,
  HangSapVeRoute: HangSapVeRoute,
  HoanHangRoute: HoanHangRoute,
  KiemKeRoute: KiemKeRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRoute,
  NgoaiLeRoute: NgoaiLeRoute,
  NhapKhoLuanChuyenRoute: NhapKhoLuanChuyenRoute,
  NhomQuyenRoute: NhomQuyenRoute,
  PhienDangNhapRoute: PhienDangNhapRoute,
  PhieuThuRoute: PhieuThuRoute,
  PhuPhiRoute: PhuPhiRoute,
  PodQuayRoute: PodQuayRoute,
  QuanLyDonCodRoute: QuanLyDonCodRoute,
  QuanLyHoaDonRoute: QuanLyHoaDonRoute,
  QuetNhapRoute: QuetNhapRoute,
  QuetXuatRoute: QuetXuatRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TacVuRoute: TacVuRoute,
  TaiKhoanRoute: TaiKhoanRoute,
  TaoDonRoute: TaoDonRoute,
  TichHopRoute: TichHopRoute,
  TonKhoRoute: TonKhoRoute,
  TraCuuRoute: TraCuuRoute,
  LayHangRoute: LayHangRoute,
  ManHinhQrKeyRoute: ManHinhQrKeyRoute,
  VanDonRoute: VanDonRoute,
  TaoDonVpRoute: TaoDonVpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
